package net.student.studentportal.controller;

import net.student.studentportal.entity.StudentEntry;
import net.student.studentportal.repository.StudentRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Optional;

@RestController
@RequestMapping("/Student")
@CrossOrigin(origins = "http://localhost:3000")  // React frontend origin
public class StudentController {

    @Autowired
    private StudentRepository studentRepository;

    @GetMapping("/hello")
    public String hello() {
        return "hi to all";
    }

    @GetMapping("/details")
    public List<StudentEntry> getAllStudents() {
        return studentRepository.findAll();
    }

    @PostMapping("/entry")
    public StudentEntry createStudent(@RequestBody StudentEntry student) {
        // ID will be auto-generated by DB, no need to set manually
        return studentRepository.save(student);
    }

    @GetMapping("/{id}")
    public StudentEntry getStudentById(@PathVariable Long id) {
        return studentRepository.findById(id).orElse(null);
    }

    @PutMapping("/{id}")
    public ResponseEntity<StudentEntry> updateStudentById(
            @PathVariable Long id,
            @RequestBody StudentEntry updatedStudent) {

        Optional<StudentEntry> optionalStudent = studentRepository.findById(id);

        if (optionalStudent.isPresent()) {
            StudentEntry existingStudent = optionalStudent.get();

            existingStudent.setName(updatedStudent.getName());
            existingStudent.setGender(updatedStudent.getGender());
            existingStudent.setNatonality(updatedStudent.getNatonality()); // fixed spelling
            existingStudent.setAadhaarnumber(updatedStudent.getAadhaarnumber());
            existingStudent.setPhone_number(updatedStudent.getPhone_number());
            existingStudent.setEmail(updatedStudent.getEmail());
            existingStudent.setAddress(updatedStudent.getAddress());

            StudentEntry savedStudent = studentRepository.save(existingStudent);
            return ResponseEntity.ok(savedStudent);

        } else {
            // Return 404 Not Found if student does not exist
            return ResponseEntity.notFound().build();
        }
    }


    @DeleteMapping("/{id}")
    public String deleteStudentById(@PathVariable Long id) {
        studentRepository.deleteById(id);
        return "Student with ID " + id + " has been deleted.";
    }
}
